# Data Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/jrchen/flatiron-ds-course/Milestones/dsc-phase-3-project-online/data/all-states-history.csv')
df.head()

,date,state,dataQualityGrade,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2020-11-09,AK,A,84.0,84.0,0,NaN,NaN,NaN,119.0,...,767997.0,-13304,NaN,NaN,NaN,NaN,NaN,0,767997.0,-13304
1,2020-11-09,AL,A,3084.0,2865.0,0,219.0,21294.0,21294.0,1174.0,...,1406829.0,4138,NaN,NaN,66370.0,NaN,NaN,0,1406829.0,4138
2,2020-11-09,AR,A+,2108.0,1930.0,23,178.0,7496.0,7496.0,786.0,...,1436416.0,8545,NaN,21856.0,NaN,77969.0,NaN,0,1436416.0,8545
3,2020-11-09,AS,D,0.0,NaN,0,NaN,NaN,NaN,NaN,...,1768.0,0,NaN,NaN,NaN,NaN,NaN,0,1768.0,0
4,2020-11-09,AZ,A+,6164.0,5745.0,0,419.0,22211.0,22211.0,1232.0,...,1883207.0,10547,325589.0,NaN,NaN,NaN,1883207.0,10547,NaN,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14111 entries, 0 to 14110
Data columns (total 42 columns):
date                                14111 non-null object
state                               14111 non-null object
dataQualityGrade                    12860 non-null object
death                               13293 non-null float64
deathConfirmed                      5959 non-null float64
deathIncrease                       14111 non-null int64
deathProbable                       4375 non-null float64
hospitalized                        8190 non-null float64
hospitalizedCumulative              8190 non-null float64
hospitalizedCurrently               11083 non-null float64
hospitalizedIncrease                14111 non-null int64
inIcuCumulative                     2376 non-null float64
inIcuCurrently                      6541 non-null float64
negative                            13810 non-null float64
negativeIncrease                    14111 non-null int64
negativeTestsAntibody               832 non-null float64
negativeTestsPeopleAntibody         660 non-null float64
negativeTestsViral                  3003 non-null float64
onVentilatorCumulative              821 non-null float64
onVentilatorCurrently               5363 non-null float64
positive                            13978 non-null float64
positiveCasesViral                  10915 non-null float64
positiveIncrease                    14111 non-null int64
positiveScore                       14111 non-null int64
positiveTestsAntibody               1893 non-null float64
positiveTestsAntigen                515 non-null float64
positiveTestsPeopleAntibody         664 non-null float64
positiveTestsPeopleAntigen          286 non-null float64
positiveTestsViral                  4308 non-null float64
recovered                           10008 non-null float64
totalTestEncountersViral            3254 non-null float64
totalTestEncountersViralIncrease    14111 non-null int64
totalTestResults                    14076 non-null float64
totalTestResultsIncrease            14111 non-null int64
totalTestsAntibody                  2584 non-null float64
totalTestsAntigen                   775 non-null float64
totalTestsPeopleAntibody            1069 non-null float64
totalTestsPeopleAntigen             409 non-null float64
totalTestsPeopleViral               5928 non-null float64
totalTestsPeopleViralIncrease       14111 non-null int64
totalTestsViral                     8715 non-null float64
totalTestsViralIncrease             14111 non-null int64
dtypes: float64(30), int64(9), object(3)
memory usage: 4.5+ MB

In [4]:
df.shape

(14111, 42)

# Check NA Value

In [5]:
df.isna().sum() / df.shape[0]

date                                0.000000
state                               0.000000
dataQualityGrade                    0.088654
death                               0.057969
deathConfirmed                      0.577705
deathIncrease                       0.000000
deathProbable                       0.689958
hospitalized                        0.419602
hospitalizedCumulative              0.419602
hospitalizedCurrently               0.214584
hospitalizedIncrease                0.000000
inIcuCumulative                     0.831621
inIcuCurrently                      0.536461
negative                            0.021331
negativeIncrease                    0.000000
negativeTestsAntibody               0.941039
negativeTestsPeopleAntibody         0.953228
negativeTestsViral                  0.787187
onVentilatorCumulative              0.941818
onVentilatorCurrently               0.619942
positive                            0.009425
positiveCasesViral                  0.226490
positiveIncrease                    0.000000
positiveScore                       0.000000
positiveTestsAntibody               0.865849
positiveTestsAntigen                0.963504
positiveTestsPeopleAntibody         0.952945
positiveTestsPeopleAntigen          0.979732
positiveTestsViral                  0.694706
recovered                           0.290766
totalTestEncountersViral            0.769400
totalTestEncountersViralIncrease    0.000000
totalTestResults                    0.002480
totalTestResultsIncrease            0.000000
totalTestsAntibody                  0.816880
totalTestsAntigen                   0.945078
totalTestsPeopleAntibody            0.924243
totalTestsPeopleAntigen             0.971016
totalTestsPeopleViral               0.579902
totalTestsPeopleViralIncrease       0.000000
totalTestsViral                     0.382397
totalTestsViralIncrease             0.000000
dtype: float64

In [6]:
# check columns
na_dict = {}
for i in df.columns:
    na_dict[i] = df[i].isna().sum() / df.shape[0]

In [7]:
sort_na = sorted(na_dict.items(), key=lambda x: x[1], reverse=True)

In [8]:
sort_na

[('positiveTestsPeopleAntigen', 0.9797321238749911),
 ('totalTestsPeopleAntigen', 0.9710155198072425),
 ('positiveTestsAntigen', 0.9635036496350365),
 ('negativeTestsPeopleAntibody', 0.9532279781730565),
 ('positiveTestsPeopleAntibody', 0.9529445113741053),
 ('totalTestsAntigen', 0.9450783077032102),
 ('onVentilatorCumulative', 0.9418184395152718),
 ('negativeTestsAntibody', 0.9410389058181561),
 ('totalTestsPeopleAntibody', 0.924243497980299),
 ('positiveTestsAntibody', 0.8658493373963575),
 ('inIcuCumulative', 0.8316207214230034),
 ('totalTestsAntibody', 0.8168804478775423),
 ('negativeTestsViral', 0.7871873006874069),
 ('totalTestEncountersViral', 0.7693997590532209),
 ('positiveTestsViral', 0.6947062575295868),
 ('deathProbable', 0.6899581886471547),
 ('onVentilatorCurrently', 0.619941889306215),
 ('totalTestsPeopleViral', 0.5799022039543619),
 ('deathConfirmed', 0.5777053362624902),
 ('inIcuCurrently', 0.5364609170150946),
 ('hospitalized', 0.4196017291474736),
 ('hospitalizedCumulative', 0.4196017291474736),
 ('totalTestsViral', 0.3823967117851322),
 ('recovered', 0.2907660690241655),
 ('positiveCasesViral', 0.2264899723619871),
 ('hospitalizedCurrently', 0.21458436680603785),
 ('dataQualityGrade', 0.0886542413719793),
 ('death', 0.05796896038551485),
 ('negative', 0.021330876621075755),
 ('positive', 0.009425271065126497),
 ('totalTestResults', 0.0024803344908227625),
 ('date', 0.0),
 ('state', 0.0),
 ('deathIncrease', 0.0),
 ('hospitalizedIncrease', 0.0),
 ('negativeIncrease', 0.0),
 ('positiveIncrease', 0.0),
 ('positiveScore', 0.0),
 ('totalTestEncountersViralIncrease', 0.0),
 ('totalTestResultsIncrease', 0.0),
 ('totalTestsPeopleViralIncrease', 0.0),
 ('totalTestsViralIncrease', 0.0)]

In [9]:
# Drop columns with over 30% na values
drop_columns = []
for i in df.columns:
    if df[i].isna().sum()/df.shape[0] > 0.3:
        drop_columns.append(i)

In [10]:
df.drop(columns=drop_columns, inplace=True)

In [11]:
# check data
df.shape

(14111, 19)

In [12]:
# drop the remaining na values by row
df.dropna(inplace=True)
df.shape

(8006, 19)

In [13]:
df.head()

,date,state,dataQualityGrade,death,deathIncrease,hospitalizedCurrently,hospitalizedIncrease,negative,negativeIncrease,positive,positiveCasesViral,positiveIncrease,positiveScore,recovered,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsPeopleViralIncrease,totalTestsViralIncrease
0,2020-11-09,AK,A,84.0,0,119.0,0,747697.0,-14905,20300.0,20300.0,474,0,7161.0,0,767997.0,-13304,0,-13304
1,2020-11-09,AL,A,3084.0,0,1174.0,0,1232975.0,3158,204857.0,173854.0,1170,0,84471.0,0,1406829.0,4138,0,4138
2,2020-11-09,AR,A+,2108.0,23,786.0,62,1324655.0,7716,122811.0,111761.0,945,0,108201.0,0,1436416.0,8545,0,8545
4,2020-11-09,AZ,A+,6164.0,0,1232.0,9,1630206.0,10142,259699.0,253001.0,435,0,43460.0,0,1883207.0,10547,10547,0
6,2020-11-09,CO,A,2168.0,0,1134.0,20,1210972.0,10965,130984.0,123351.0,3017,0,8667.0,30597,2245385.0,30597,13934,0

# Columns Describe

The whole definition link: https://covidtracking.com/about-data/data-definitions

* dataQualityGrade: To help members of the public understand how well each state is performing, we have assigned each state a data-quality grade based on our assessment of the completeness of their reporting. Our original state grades were based on the presence of the most basic categories of data, and failed to capture our current understanding of “completeness,” so we have updated our grading system accordingly.
* Positive: Total number of confirmed plus probable cases of COVID-19 reported by the state or territory, ideally per the August 5, 2020 CSTE case definition.
* PositiveCasesViral: Total number of unique people with a positive PCR or other approved nucleic acid amplification test (NAAT), as reported by the state or territory.
* hospitalizedIncrease: Daily increase in hospitalizedCumulative, calculated from the previous day’s value.
* deathIncrease: Daily increase in death, calculated from the previous day’s value.

# Check duplicate values

In [14]:
df.duplicated().sum()

0

# Check any erroneous values

In [15]:
df.describe()

,death,deathIncrease,hospitalizedCurrently,hospitalizedIncrease,negative,negativeIncrease,positive,positiveCasesViral,positiveIncrease,positiveScore,recovered,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsPeopleViralIncrease,totalTestsViralIncrease
count,8006.000000,8006.000000,8006.000000,8006.000000,8.006000e+03,8006.000000,8006.000000,8006.000000,8006.000000,8006.0,8006.000000,8.006000e+03,8.006000e+03,8006.000000,8006.000000,8.006000e+03
mean,2685.113415,13.573445,615.705721,31.118536,9.028650e+05,10157.565576,75260.056208,73424.597677,707.899076,0.0,39315.278166,3.926160e+03,1.064765e+06,12379.425931,2826.243068,8.434750e+03
std,4745.110301,31.288188,1050.759118,256.560875,1.449188e+06,17496.255819,110478.624090,109660.791280,1088.538110,0.0,77856.771640,1.926816e+04,1.584727e+06,18609.625327,16386.924969,3.396245e+04
min,1.000000,-213.000000,0.000000,-4124.000000,1.308000e+03,-340903.000000,141.000000,137.000000,-7757.000000,0.0,11.000000,0.000000e+00,1.449000e+03,-336892.000000,-528635.000000,-4.415930e+05
25%,212.000000,1.000000,93.000000,0.000000,1.658190e+05,1588.000000,9105.500000,8924.250000,104.000000,0.0,3330.250000,0.000000e+00,2.108390e+05,2601.250000,0.000000,0.000000e+00
50%,824.500000,5.000000,341.000000,3.000000,4.297695e+05,4864.500000,36251.500000,35499.000000,410.000000,0.0,11211.500000,0.000000e+00,5.342355e+05,6419.000000,0.000000,2.370500e+03
75%,2957.750000,15.000000,741.000000,31.000000,1.044678e+06,11549.000000,103094.000000,99423.500000,888.000000,0.0,48549.500000,0.000000e+00,1.257509e+06,14564.750000,3409.250000,8.853500e+03
max,25973.000000,951.000000,10993.000000,16373.000000,1.524405e+07,166478.000000,963019.000000,963019.000000,17820.000000,0.0,820215.000000,1.225113e+06,1.577623e+07,168353.000000,820817.000000,2.352923e+06

In [16]:
# drop some '0' columns
df.drop(columns=['positiveScore', 'totalTestEncountersViralIncrease'], inplace=True)

In [17]:
# drop some rows with erroneous values 
columns = ['deathIncrease', 'hospitalizedIncrease', 'negativeIncrease', 'negativeIncrease', 'positiveIncrease', 
           'totalTestResultsIncrease', 'totalTestsPeopleViralIncrease', 'totalTestsViralIncrease']
for i in columns:
    a = df.loc[df[i] < 0]
    a.reset_index(inplace=True)
    drop_rows = a['index']
    df.drop(index=drop_rows, inplace=True)

In [18]:
df.describe()

,death,deathIncrease,hospitalizedCurrently,hospitalizedIncrease,negative,negativeIncrease,positive,positiveCasesViral,positiveIncrease,recovered,totalTestResults,totalTestResultsIncrease,totalTestsPeopleViralIncrease,totalTestsViralIncrease
count,7848.000000,7848.000000,7848.000000,7848.000000,7.848000e+03,7848.000000,7848.000000,7848.000000,7848.000000,7848.000000,7.848000e+03,7848.000000,7848.000000,7.848000e+03
mean,2697.690240,13.756626,619.650612,32.450943,9.101826e+05,10376.275229,75665.605759,73828.007390,715.622324,39693.192151,1.073445e+06,12592.208461,3089.970438,8.664066e+03
std,4768.100689,31.395688,1057.981393,253.344320,1.459462e+06,16721.306715,110977.252791,110163.630126,1091.398648,78266.889113,1.595635e+06,18021.230078,12569.000905,3.154100e+04
min,1.000000,0.000000,0.000000,0.000000,1.308000e+03,0.000000,141.000000,137.000000,0.000000,11.000000,1.449000e+03,0.000000,0.000000,0.000000e+00
25%,213.000000,1.000000,94.750000,0.000000,1.670785e+05,1624.750000,9248.500000,9068.750000,106.000000,3346.000000,2.130140e+05,2652.750000,0.000000,0.000000e+00
50%,829.000000,5.000000,343.000000,3.000000,4.348380e+05,4922.000000,36496.500000,35779.500000,414.000000,11395.000000,5.396815e+05,6470.500000,0.000000,2.493500e+03
75%,2967.250000,15.000000,744.250000,32.000000,1.055481e+06,11684.000000,103457.750000,99705.500000,894.000000,49750.500000,1.267424e+06,14747.500000,3427.250000,8.941000e+03
max,25973.000000,951.000000,10993.000000,16373.000000,1.524405e+07,166478.000000,963019.000000,963019.000000,17820.000000,820215.000000,1.577623e+07,168353.000000,820817.000000,2.352923e+06

In [19]:
# drop some less informative columns
df.drop(columns=['date', 'dataQualityGrade'], inplace=True)

In [20]:
df.to_csv("/Users/jrchen/flatiron-ds-course/Milestones/dsc-phase-3-project-online/data/clean_data.csv")